### ISSUE TITLE
[BUG] OpenApiGatewayPythonProject Intermittent CodeBuild failure

### ISSUE THREAD

**Issue by jessieweiyi** [aws/aws-pdk#171]
### Describe the bug

We are using OpenApiGatewayPythonProject and PDKPipeline project. There are some intermittent CodeBuild failures in the CodePipeline synth stage (around 1/3 builds failed). Although click the release change to rerun the pipeline may make the build pass, it is annoying that it may be failed again after rerun. 

There are 2 type of intermittent errors. I think they may be related. Seems like all related to the installation of *api-python module. 

* Intermittent Error 1: 

INSTALL | Failed | COMMAND_EXECUTION_ERROR: Error while executing command: yarn install --frozen-lockfile \|\| npx projen && yarn install --frozen-lockfile. Reason: exit status 1
-- | -- | --

``` 
👾 install | pip install --editable .
Obtaining file:///codebuild/output/src937497960/src/packages/project_name_api/generated/python
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: urllib3>=1.15 in /codebuild/output/src937497960/src/.env/lib/python3.9/site-packages (from project-name-api-python==1.0.0) (1.26.12)
Requirement already satisfied: certifi in /codebuild/output/src937497960/src/.env/lib/python3.9/site-packages (from project-name-api-python==1.0.0) (2022.9.24)
Requirement already satisfied: python-dateutil in /codebuild/output/src937497960/src/.env/lib/python3.9/site-packages (from project-name-api-python==1.0.0) (2.8.2)
Requirement already satisfied: frozendict>=2.0.3 in /codebuild/output/src937497960/src/.env/lib/python3.9/site-packages (from project-name-api-python==1.0.0) (2.3.4)
Requirement already satisfied: six>=1.5 in /codebuild/output/src937497960/src/.env/lib/python3.9/site-packages (from python-dateutil->project-name-api-python==1.0.0) (1.16.0)
Installing collected packages: project-name-api-python
  Attempting uninstall: project-name-api-python
    Found existing installation: project-name-api-python 1.0.0
    Uninstalling project-name-api-python-1.0.0:
      Successfully uninstalled project-name-api-python-1.0.0
  Running setup.py develop for project-name-api-python
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [2 lines of output]
        running develop
        error: [Errno 2] No such file or directory: '/codebuild/output/src937497960/src/.env/lib/python3.9/site-packages/project-name-api.egg-link'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of project-name-api-python
  Moving to /codebuild/output/src937497960/src/.env/lib/python3.9/site-packages/project-name-api-python.egg-link
   from /tmp/pip-uninstall-nd55vfjv/project-name-api-python.egg-link
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [2 lines of output]
    running develop
    error: [Errno 2] No such file or directory: '/codebuild/output/src937497960/src/.env/lib/python3.9/site-packages/project-name-api.egg-link'
    [end of output]
   ```

* Intermittent Error 2: 

BUILD | Failed | COMMAND_EXECUTION_ERROR: Error while executing command: npx nx run-many --target=build --all. Reason: exit status 1
-- | -- | --

```
> nx run infra:build

·[1Gyarn run v1.22.19
·[1G$ npx projen build
👾 build » post-compile » synth:silent | cdk synth -q
Traceback (most recent call last):
  File "/codebuild/output/src425806827/src/packages/infra/infra/pipeline.py", line 4, in <module>
    from application_stage import ApplicationStage
  File "/codebuild/output/src425806827/src/packages/infra/infra/application_stage.py", line 3, in <module>
    from application_stack import ApplicationStack
  File "/codebuild/output/src425806827/src/packages/infra/infra/application_stack.py", line 10, in <module>
    from project_name_api import ProjectNameApi
  File "/codebuild/output/src425806827/src/packages/project_name_api/project_name_api/__init__.py", line 1, in <module>
    from .api.project_name_api import ProjectNameApi
  File "/codebuild/output/src425806827/src/packages/project_name_api/project_name_api/api/project_name_api.py", line 2, in <module>
    from project_name_api_python.apis.tags.default_api_operation_config import OperationConfig
ModuleNotFoundError: No module named 'project_name_api_python'

Subprocess exited with error 1
👾 Task "build » post-compile » synth:silent" failed when executing "cdk synth -q" (cwd: /codebuild/output/src425806827/src/packages/infra)
·[1Gerror Command failed with exit code 1.
·[1Ginfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 
 >  NX   Running target "build" failed

   Failed tasks:
   
   - infra:build

```

### Expected Behavior

It should have consistent build results. 

### Current Behavior

1/3 builds failed due to the 2 reasons above

### Reproduction Steps

They are intermittent errors. Just try a few times in your CodePipeline. you may reproduce it. 

### Additional Information/Context

projenrc file

```
import { pipeline, nx_monorepo } from 'aws-prototyping-sdk';
import { ApprovalLevel } from 'projen/lib/awscdk';
import { VenvOptions } from 'projen/lib/python';
import { OpenApiGatewayPythonProject, ClientLanguage } from '@aws-prototyping-sdk/open-api-gateway';

const sharedEnv: VenvOptions = {
  envdir: '../../.env',
};

const monorepo = new nx_monorepo.NxMonorepoProject({
  defaultReleaseBranch: 'mainline',
  devDeps: ['aws-prototyping-sdk@0.11.1'],
  deps: [
    '@aws-prototyping-sdk/cloudscape-react-ts-website@0.11.1', 
    '@aws-prototyping-sdk/open-api-gateway@0.11.1',
  ],
  gitignore: [".env", ".ipynb_checkpoints", "xgboost-model"],
  name: 'project_name',
  tsconfig: {
    compilerOptions: {},
    include: [
      "packages/**/*.ts",
      "packages/**/*.tsx",
    ]
  }
});

const apiProject = new OpenApiGatewayPythonProject({
  parent: monorepo,
  outdir: 'packages/project_name_api',
  name: 'project-name-api',
  moduleName: 'project_name_api',
  version: '1.0.0',
  authorName: '',
  authorEmail: '',
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  venvOptions: sharedEnv,
  deps: [
    'aws-prototyping-sdk.open-api-gateway@0.11.1',
  ]
});

apiProject.tasks.tryFind('install')!.exec('pip install --editable .');

const pipelineProject = new pipeline.PDKPipelinePyProject({
  authorEmail: '',
  authorName: '',
  cdkVersion: '2.0.0',
  moduleName: 'infra',
  name: 'infra',
  version: '0.0.0',
  requireApproval: ApprovalLevel.NEVER,
  parent: monorepo,
  outdir: 'packages/infra',
  appEntrypoint: 'infra/pipeline.py',
  deps: [
    "aws-prototyping-sdk.identity@0.11.1",
    "aws-prototyping-sdk.static-website@0.11.1", 
    "aws-cdk.aws-lambda-python-alpha",
    apiProject.name
  ],
  venvOptions: sharedEnv,
});

const pipelineProjectTestTask = pipelineProject.tasks.tryFind("test");
pipelineProjectTestTask?.reset();
pipelineProjectTestTask?.exec("pytest tests/");

monorepo.addImplicitDependency(pipelineProject, apiProject);

monorepo.synth();
```

### PDK version used

0.11.1

### What languages are you seeing this issue on?

Python

### Environment details (OS name and version, etc.)

CodeBuild provisioned by PDKPipeline

**Comment by cogwirrel** [comment]
Thank you for raising this!

I've been playing around with this and have experienced the same non-deterministic behaviour in a pipeline too. This seems to be a general problem with having multiple python projects within a projen project rather than something specific to `open-api-gateway`.

The issue appears to be the non-deterministic nature of `yarn install`. `yarn install` will install all the required node_modules, then will run the `install` task for all packages in the workspace _in parallel_.

Because there are multiple python projects in your monorepo, the parallel `pip install` commands can conflict - sometimes running in the wrong order, causing "Intermittent error 1" - eg here the it looks like the `pip install requirements.txt` for the api project is running at the same time as the `pip install --editable .` for the generated python client project, so the api project install fails because the python client does not exist yet.

I think "Intermittent error 2" is a similar problem, where we get further and the installs complete without clashing, but the virtualenv ends up in a non-deterministic state where some of the local package dependencies don't exist.

I was able to get a build which consistently passes by moving the `install` tasks into the `pre-compile` task instead. This means that the task is run by `nx` which has awareness of the dependencies and can therefore run the `install` commands in the correct order. This can be done in your `.projenrc.ts` like so:

```ts
myPythonProject.tasks.tryFind('install')!.steps.forEach((step) => myPythonProject.preCompileTask.exec(step.exec!));
myPythonProject.tasks.tryFind('install')!.reset();
```

Here's a full example `.projenrc.ts` with the workaround applied to a simple `OpenApiGatewayPythonProject`:

```ts
import { nx_monorepo } from "aws-prototyping-sdk";
import { ClientLanguage, OpenApiGatewayPythonProject } from "@aws-prototyping-sdk/open-api-gateway";
import { PDKPipelinePyProject } from "aws-prototyping-sdk/pipeline";

const monorepo = new nx_monorepo.NxMonorepoProject({
  defaultReleaseBranch: "main",
  devDeps: ["aws-prototyping-sdk", "@aws-prototyping-sdk/open-api-gateway"],
  name: "python-test",
});

monorepo.gitignore.addPatterns('.idea', '*.iml', '.env');

const api = new OpenApiGatewayPythonProject({
  authorEmail: "", authorName: "",
  clientLanguages: [ClientLanguage.PYTHON],
  moduleName: "thisismyapi",
  name: "thisismyapi",
  version: "1.0.0",
  parent: monorepo,
  outdir: 'packages/thisismyapi',
  venvOptions: {
    envdir: '../../.env',
  },
});

api.tasks.tryFind('install')!.steps.forEach((step) => api.preCompileTask.exec(step.exec!));
api.tasks.tryFind('install')!.reset();

api.preCompileTask.exec('pip install --editable .');

const infra = new PDKPipelinePyProject({
  authorEmail: "", authorName: "",
  moduleName: "thisismypipeline",
  name: "thisismypipeline",
  version: "1.0.0",
  parent: monorepo,
  outdir: 'packages/infra',
  cdkVersion: "2.0.0",
  deps: [api.name],
  venvOptions: {
    envdir: '../../.env',
  },
  pytest: false,
});

monorepo.addImplicitDependency(infra, api);

infra.tasks.tryFind('install')!.steps.forEach((step) => infra.preCompileTask.exec(step.exec!));
infra.tasks.tryFind('install')!.reset();

monorepo.synth();
```

Note that in the above example there's also a generated python client which runs `pip install ...` as part of the `install` task - but we can't edit its install task because it's synthesized early. This is fine however as it's the only python project which is installed during `yarn install` and so doesn't clash with any others.

The ultimate fix for this is to change how we run the install task for any `PythonProject`s that are added to the nx-monorepo. The monorepo can override the install tasks of its subprojects and ensure they run in the correct order. I'll work on a PR to implement this!
