### ISSUE TITLE
[BUG] jsii-pacmak ERR_FS_FILE_TOO_LARGE when building

### ISSUE THREAD

**Issue by jstrunk** [aws/aws-pdk#347]
### Describe the bug

When using pnpm to build the package with changes, the build failed on the jsii-pacmak step with `EFF_FS_FILE_TOO_LARGE`. After removing my changes, the error continued. The error went away after I copied my changes onto a clean clone of the repo.

### Expected Behavior

The build should have completed successfully.

### Current Behavior

```
@aws-prototyping-sdk/pipeline: 👾 build » package » package-all » package:js | jsii-pacmak -v --target js --pack-command='pnpm pack'
@aws-prototyping-sdk/pipeline: [jsii-pacmak] [INFO] Found 1 modules to package
@aws-prototyping-sdk/pipeline: [jsii-pacmak] [INFO] Packaging NPM bundles
@aws-prototyping-sdk/pipeline: Error: Command (pnpm pack ) failed with status 1:
@aws-prototyping-sdk/pipeline: #STDERR> 
@aws-prototyping-sdk/pipeline: #STDOUT>  ERR_FS_FILE_TOO_LARGE  File size (2731119967) is greater than 2 GiB
@aws-prototyping-sdk/pipeline: #STDOUT> 
@aws-prototyping-sdk/pipeline: #STDOUT> pnpm [ERR_FS_FILE_TOO_LARGE]: File size (2731119967) is greater than 2 GiB
@aws-prototyping-sdk/pipeline: #STDOUT>     at new NodeError (node:internal/errors:399:5)
@aws-prototyping-sdk/pipeline: #STDOUT>     at tryCreateBuffer (node:fs:435:13)
@aws-prototyping-sdk/pipeline: #STDOUT>     at Object.readFileSync (node:fs:480:14)
@aws-prototyping-sdk/pipeline: #STDOUT>     at packPkg (/Users/<user>/.nvm/versions/node/v18.15.0/lib/node_modules/pnpm/dist/pnpm.cjs:211773:56)
@aws-prototyping-sdk/pipeline: #STDOUT>     at async Object.handler [as pack] (/Users/<user>/.nvm/versions/node/v18.15.0/lib/node_modules/pnpm/dist/pnpm.cjs:211734:7)
@aws-prototyping-sdk/pipeline: #STDOUT>     at async /Users/<user>/.nvm/versions/node/v18.15.0/lib/node_modules/pnpm/dist/pnpm.cjs:221644:21
@aws-prototyping-sdk/pipeline: #STDOUT>     at async main (/Users/<user>/.nvm/versions/node/v18.15.0/lib/node_modules/pnpm/dist/pnpm.cjs:221611:34)
@aws-prototyping-sdk/pipeline: #STDOUT>     at async runPnpm (/Users/<user>/.nvm/versions/node/v18.15.0/lib/node_modules/pnpm/dist/pnpm.cjs:221866:5)
@aws-prototyping-sdk/pipeline: #STDOUT>     at async /Users/<user>/.nvm/versions/node/v18.15.0/lib/node_modules/pnpm/dist/pnpm.cjs:221858:7
@aws-prototyping-sdk/pipeline: #STDOUT> 
@aws-prototyping-sdk/pipeline:     at ChildProcess.<anonymous> (/Users/<user>/Documents/code/aws-prototyping-sdk/node_modules/.pnpm/jsii-pacmak@1.80.0/node_modules/jsii-pacmak/lib/util.js:175:27)
@aws-prototyping-sdk/pipeline:     at Object.onceWrapper (node:events:628:26)
@aws-prototyping-sdk/pipeline:     at ChildProcess.emit (node:events:513:28)
@aws-prototyping-sdk/pipeline:     at maybeClose (node:internal/child_process:1091:16)
@aws-prototyping-sdk/pipeline:     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
@aws-prototyping-sdk/pipeline: 👾 Task "build » package » package-all » package:js" failed when executing "jsii-pacmak -v --target js --pack-command='pnpm pack'" (cwd: /Users/<user>/Documents/code/aws-prototyping-sdk/packages/pipeline)
```

### Reproduction Steps

I'm not sure what caused the behavior. The only change I made to projenrc was to add `@aws-cdk/aws-lambda-python-alpha` as a dependency to the pipeline package.

### Possible Solution

@agdimech suggested deleting the dist folder in packages/aws-prototyping-sdk.

### PDK version used

0.15.0

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS 12.6.4

**Comment by agdimech** [comment]
Resolved in #384
