### ISSUE TITLE
[BUG] eslint fails on new projen nx-monorepo

### ISSUE THREAD

**Issue by JeremyJonas** [aws/aws-pdk#388]
### Describe the bug

Getting eslint issue during `npx projen new --from @aws-prototyping-sdk/nx-monorepo` execution, and by calling `yarn eslint` directly after this.

```

yarn run v1.22.19
$ xxx/node_modules/.bin/nx run-many --target=eslint --output-style=stream --nx-bail
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: npm run eslint --if-present
👾 eslint | yarn nx run-many --target=eslint --output-style=stream --nx-bail
xxx/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs:293
const wrap = require('wrap-ansi');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module xxx/node_modules/wrap-ansi/index.js from xxx/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /xxx/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/xxx/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs:293:14)
    at Object.<anonymous> (/xxx/node_modules/nx/node_modules/yargs/build/index.cjs:1:60678)
    at Object.<anonymous> (/xxx/node_modules/nx/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/xxx/node_modules/nx/src/command-line/nx-commands.js:8:15)
    at Object.<anonymous> (/xxx/node_modules/nx/bin/init-local.js:7:23)
    at Object.<anonymous> (/xxx/node_modules/nx/bin/nx.js:6:22) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.15.0
error Command failed with exit code 1.
👾 Task "eslint" failed when executing "yarn nx run-many --target=eslint --output-style=stream --nx-bail" (cwd: /xxx/)

    at checkExecSyncError (node:child_process:885:11)
    at Object.exec
```

### Expected Behavior

Should not throw error.

### Current Behavior

Throws the above error.

### Reproduction Steps

1. Create a folder
2. CD into folder (empty)
3. Run `npx projen new --from @aws-prototyping-sdk/nx-monorepo`
4. Get error

### PDK version used

v1.22.19

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

macos

**Comment by JeremyJonas** [comment]
Getting same error with the following as well, seems not related to eslint at all.

```
npx nx run-many --target=build --all
/Users/jerjonas/workspaces/COPE/projects/PDK/testing/bug/issue-382/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs:293
const wrap = require('wrap-ansi');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module
```

**Comment by JeremyJonas** [comment]
## Workarounds

Delete the yarn.lock file and re-run yarn

**Comment by JeremyJonas** [comment]
Seems to be related to #382

**Comment by agdimech** [comment]
This is only happening with yarn 1.x and is related to https://github.com/yarnpkg/yarn/issues/6907. What is happening in the NXMonorepo is due to the recent change where we call `installDependencies` followed by `resolveDepsAndWritePackageJson`, this now triggers two `yarn install` commands to run. The first will run without reading from a lockfile, whereas the second one will. Yarn 1.x seems to have an issue with aliases and non-deterministic behaviour which can be proven by running the following script:

```
npx projen new --from @aws-prototyping-sdk/nx-monorepo nx-monorepo --no-git # will fail
rm -rf node_modules
yarn --no-lockfile
yarn eslint # will succeed as it wasn't resolved from the lock file
```

I assume the following 'fix' should work if we add it to NxMonorepo:

```
this.package.addPackageResolutions(
  "wrap-ansi@^7.0.0",
  "@zkochan/js-yaml@npm:js-yaml@4.1.0"
);
```
