### ISSUE TITLE
[BUG] Multibranch repo feature introduce regression for update mutation buildspec

### ISSUE THREAD

**Issue by mteichtahl** [aws/aws-pdk#414]
### Describe the bug

Updated buildspec does not respect branch name prefix for pipelineStack

Likely introduced in  #403 

```
No stacks match the name(s) PipelineStack
--
112 | [05:05:37] Error: No stacks match the name(s) PipelineStack
113 | at CdkToolkit.validateStacksSelected (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:3959)
114 | at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:2861)
115 | at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:400:142691)
116 | at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:455:51984)
117 |  
118 | [Container] 2023/05/17 05:05:37 Command did not exit successfully cdk -a . deploy PipelineStack --require-approval=never --verbose exit status 1
```

### Expected Behavior

pipeline mutation should succeed

### Current Behavior

PipelineStack mutation fails with error below

```


No stacks match the name(s) PipelineStack
--
112 | [05:05:37] Error: No stacks match the name(s) PipelineStack
113 | at CdkToolkit.validateStacksSelected (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:3959)
114 | at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:2861)
115 | at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:400:142691)
116 | at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:455:51984)
117 |  
118 | [Container] 2023/05/17 05:05:37 Command did not exit successfully cdk -a . deploy PipelineStack --require-approval=never --verbose exit status 1


```

### Reproduction Steps

use mainline branch as the default branch

```
this.pipeline = new PDKPipeline(this, "ApplicationPipeline", {
      primarySynthDirectory: "packages/cicd/cdk.out",
      repositoryName: this.node.tryGetContext("repositoryName") || "monorepo",
      defaultBranchName:
        this.node.tryGetContext("defaultBranchName") ||
        PDKPipeline.defaultBranchName,
      publishAssetsInParallel: false,
      crossAccountKeys: true,
      synth: {}
})
```

```
new PDKPipelineTsProject({
  parent: project,
  cdkVersion: "2.79.1",
  outdir: "packages/cicd",
  defaultReleaseBranch: "main",
  devDeps: ["@aws-prototyping-sdk/pipeline", "@types/node"],
  packageManager: javascript.NodePackageManager.YARN2,
  name: "cicd",
  deps: [baseInfra.package.packageName],
  context: {
    repositoryName: 'galaxi-next',
    defaultBranchName: 'main'
  }
  
});
```

### Possible Solution

use branch name in when generating buildspec

### PDK version used

latest

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

N/A

**Comment by agdimech** [comment]
@jstrunk - Looks like this logic is off; https://github.com/aws/aws-prototyping-sdk/blob/mainline/packages/pipeline/src/pdk-pipeline.ts#LL166C17-L166C32

isDefaultBranch should return true if the user has defined a defaultBranch in the context.

**Comment by jstrunk** [comment]
Hi,

The first thing I see is that @mteichtahl wants `mainline` to be the default branch, but in `PDKPipelineTsProject` he set both `defaultReleaseBranch` and `context.defaultBranchName` to `main`.

I walked through the logic of that function again, and it does what it is supposed to do. I think that function may deserve to be more verbose or have more comments because the statement is written to find branches that are not the default branch and return the opposite.

```ts
  public static isDefaultBranch(
    props: IsDefaultBranchProps = {
      defaultBranchName: undefined,
      node: undefined,
    }
  ): boolean {
    // First, if `BRANCH` is not set, this is the default branch. The statement evaluates to false
    // and returns true. This is the main reason I wrote it in the negative.
    return process.env.BRANCH &&
      // Otherwise, if `BRANCH` is not equal to the default branch name, this is not the default branch.
      process.env.BRANCH !==
        // The default branch name can be set in three places in the following priority:
        // the props to the function
        (props.defaultBranchName ||
          // the context
          (props.node && props.node.tryGetContext("defaultBranchName")) ||
          // the hardcoded default: `mainline`
          PDKPipeline.defaultBranchName)
      ? false
      : true;
  }
```

**Comment by jstrunk** [comment]
@mteichtahl,

The only change to the buildspec should be that it sets the `BRANCH` environment variable. Can you share how you are creating `PipelineStack`? Is this a new project directly from the sample code?
