### ISSUE TITLE
[BUG] task @aws-prototyping-sdk/cdk-graph-plugin-diagram:build fails

### ISSUE THREAD

**Issue by martenpayne** [aws/aws-pdk#437]
### Describe the bug

When clean building from the repository root (after running "pnpm i"), most of the tasks complete successfully, except "@aws-prototyping-sdk/cdk-graph-plugin-diagram:build". This tasks fails with the message:
```
@aws-prototyping-sdk/cdk-graph-plugin-diagram: TypeError: Cannot read properties of undefined (reading 'resolution')
```

### Expected Behavior

Task "@aws-prototyping-sdk/cdk-graph-plugin-diagram:build" completes without error.

### Current Behavior

The stack trace for the compile error is:

```
@aws-prototyping-sdk/cdk-graph-plugin-diagram: Ran all test suites.
@aws-prototyping-sdk/cdk-graph-plugin-diagram: 👾 build » test » eslint | eslint --ext .ts,.tsx ${CI:-'--fix'} --no-error-on-unmatched-pattern src test
@aws-prototyping-sdk/cdk-graph-plugin-diagram: 👾 build » package | pdk-pnpm-link-bundled-transitive-deps packages/cdk-graph-plugin-diagram
@aws-prototyping-sdk/cdk-graph-plugin-diagram: TypeError: Cannot read properties of undefined (reading 'resolution')
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at pkgSnapshotToResolution (/Volumes/src/protos/aws-prototyping-sdk/node_modules/.pnpm/@pnpm+lockfile-utils@7.0.1/node_modules/@pnpm/lockfile-utils/src/pkgSnapshotToResolution.ts:15:26)
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at getPkgInfo (/Volumes/src/protos/aws-prototyping-sdk/node_modules/.pnpm/@pnpm+reviewing.dependencies-hierarchy@2.0.4_@pnpm+logger@5.0.0/node_modules/@pnpm/reviewing.dependencies-hierarchy/src/getPkgInfo.ts:69:40)
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at /Volumes/src/protos/aws-prototyping-sdk/node_modules/.pnpm/@pnpm+reviewing.dependencies-hierarchy@2.0.4_@pnpm+logger@5.0.0/node_modules/@pnpm/reviewing.dependencies-hierarchy/src/buildDependenciesHierarchy.ts:138:37
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at Array.forEach (<anonymous>)
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at dependenciesHierarchyForPackage (/Volumes/src/protos/aws-prototyping-sdk/node_modules/.pnpm/@pnpm+reviewing.dependencies-hierarchy@2.0.4_@pnpm+logger@5.0.0/node_modules/@pnpm/reviewing.dependencies-hierarchy/src/buildDependenciesHierarchy.ts:137:29)
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at async /Volumes/src/protos/aws-prototyping-sdk/node_modules/.pnpm/@pnpm+reviewing.dependencies-hierarchy@2.0.4_@pnpm+logger@5.0.0/node_modules/@pnpm/reviewing.dependencies-hierarchy/src/buildDependenciesHierarchy.ts:82:9
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at async Promise.all (index 0)
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at async buildDependenciesHierarchy (/Volumes/src/protos/aws-prototyping-sdk/node_modules/.pnpm/@pnpm+reviewing.dependencies-hierarchy@2.0.4_@pnpm+logger@5.0.0/node_modules/@pnpm/reviewing.dependencies-hierarchy/src/buildDependenciesHierarchy.ts:79:5)
@aws-prototyping-sdk/cdk-graph-plugin-diagram:     at async linkBundledTransitiveDeps (/Volumes/src/protos/aws-prototyping-sdk/packages/nx-monorepo/scripts/pnpm/link-bundled-transitive-deps.ts:18:32)
```

### Reproduction Steps

- ensure local repository is up to date with mainline
- clean local copy (git reset --hard && git clean -fdx)
- install packages (pnpm i)
- build (pnpm build)

### Additional Information/Context

- error happens on node v16 and v18

### PDK version used

0.19.3

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

macbook pro m2/Ventura

**Comment by martenpayne** [comment]
Issue occurs when using pnpm@8.6.0 - if I downgrade to pnpm@8.5.1, all build tasks complete without issue
