### ISSUE TITLE
[BUG] npx projen results in error related aws-cdk-lib

### ISSUE THREAD

**Issue by kwonyulchoi** [aws/aws-pdk#76]
### Describe the bug

An error related to `aws-cdk-lib` library dependency occurs when the following steps are performed. 
Note that I haven't made any changes to `.projenrc.ts` file yet.

```bash
mkdir my-project && cd my-project
npx projen new --from aws-prototyping-sdk nx-monorepo

npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
Error: Cannot find module 'aws-cdk-lib'
Require stack:
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/lib/pdk-pipeline.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/lib/index.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/index.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/index.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/.projenrc.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/src/pdk-pipeline.ts:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/ts-node/src/index.ts:1587:43)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
```

It is questionable whether a dependency error occurs even though pure nx-monorepo project has been configured, and if necessary, it seems that the dependency must be declared in advance.

For temporal purpose, I solved the problem now by running `npm i` command as a workaround.

### Expected Behavior

No error like this:

```bash
npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
```

### Current Behavior

```bash
npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
Error: Cannot find module 'aws-cdk-lib'
Require stack:
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/lib/pdk-pipeline.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/lib/index.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/index.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/index.js
- /Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/.projenrc.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/aws-prototyping-sdk/pipeline/src/pdk-pipeline.ts:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/Users/kwonyul/MyWork/source/test-projen/pdk-test-issue/node_modules/ts-node/src/index.ts:1587:43)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
```

### Reproduction Steps

Every time in the following condition:

```bash
mkdir my-project && cd my-project
npx projen new --from aws-prototyping-sdk nx-monorepo

npx projen
```

### Possible Solution

solve dependency

### Additional Information/Context

no

### PDK version used

latest 0.2.17

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

mac, node = v16.15.1

**Comment by cogwirrel** [comment]
Hi Kwonyul,

Thanks for reporting this bug!

`aws-cdk-lib` and `constructs` are now peer dependencies and so are expected to be defined by the project's package.json, but it's not a great experience with a fresh install!

I've played around with `projen new` and you can specify the deps via the command line:

```
npx projen new --from aws-prototyping-sdk nx-monorepo --deps aws-cdk-lib --deps constructs
```

I'll raise a PR to update the command in the docs!

Cheers,
Jack
