### ISSUE TITLE
[DOCS] Your First AWS PDK project fails with error

### ISSUE THREAD

**Issue by nagmesh** [aws/aws-pdk#838]
### Describe the issue

In the docs, when new app is setup. I failed on the [typesafe api step](https://aws.github.io/aws-pdk/getting_started/your_first_aws_pdk_project.html#add-a-type-safe-api-to-your-monorepo) with error 

```
myapi-typescript-runtime: 👾 build » pre-compile » generate | npx --yes -p @aws/pdk@$AWS_PDK_VERSION type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs "typescript" --metadata '{"srcDir":"src"}'
myapi-typescript-react-query-hooks: 👾 build » pre-compile » generate | npx --yes -p @aws/pdk@$AWS_PDK_VERSION type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs "typescript/templates/client" "typescript-react-query-hooks" --metadata '{"srcDir":"src"}'
myapi-typescript-runtime: node:internal/errors:497
myapi-typescript-runtime:     ErrorCaptureStackTrace(err);
myapi-typescript-runtime:     ^
myapi-typescript-runtime: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
myapi-typescript-runtime:     at new NodeError (node:internal/errors:406:5)
myapi-typescript-runtime:     at validateString (node:internal/validators:162:11)
myapi-typescript-runtime:     at Object.join (node:path:1175:7)
myapi-typescript-runtime:     at ...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45565:84
myapi-typescript-runtime:     at Array.map (<anonymous>)
myapi-typescript-runtime:     at ...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45565:65
myapi-typescript-runtime:     at Array.flatMap (<anonymous>)
myapi-typescript-runtime:     at generate_next_default (...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45562:39)
myapi-typescript-runtime:     at async ...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45587:14 {
myapi-typescript-runtime:   code: 'ERR_INVALID_ARG_TYPE'
myapi-typescript-runtime: }
myapi-typescript-runtime: Node.js v20.8.0
myapi-typescript-react-query-hooks: node:internal/errors:497
myapi-typescript-react-query-hooks:     ErrorCaptureStackTrace(err);
myapi-typescript-react-query-hooks:     ^
myapi-typescript-react-query-hooks: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
myapi-typescript-react-query-hooks:     at new NodeError (node:internal/errors:406:5)
myapi-typescript-react-query-hooks:     at validateString (node:internal/validators:162:11)
myapi-typescript-react-query-hooks:     at Object.join (node:path:1175:7)
myapi-typescript-react-query-hooks:     at ...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45565:84
myapi-typescript-react-query-hooks:     at Array.map (<anonymous>)
myapi-typescript-react-query-hooks:     at ...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45565:65
myapi-typescript-react-query-hooks:     at Array.flatMap (<anonymous>)
myapi-typescript-react-query-hooks:     at generate_next_default (...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45562:39)
myapi-typescript-react-query-hooks:     at async ...redacted/test-pdk/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45587:14 {
myapi-typescript-react-query-hooks:   code: 'ERR_INVALID_ARG_TYPE'
myapi-typescript-react-query-hooks: }
myapi-typescript-react-query-hooks: Node.js v20.8.0
myapi-typescript-runtime: 👾 Task "build » pre-compile » generate" failed when executing "npx --yes -p @aws/pdk@$AWS_PDK_VERSION type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs "typescript" --metadata '{"srcDir":"src"}'" (cwd: ...redacted/test-pdk/packages/api/generated/runtime/typescript)
myapi-typescript-react-query-hooks: 👾 Task "build » pre-compile » generate" failed when executing "npx --yes -p @aws/pdk@$AWS_PDK_VERSION type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs "typescript/templates/client" "typescript-react-query-hooks" --metadata '{"srcDir":"src"}'" (cwd: ...redacted/test-pdk/packages/api/generated/libraries/typescript-react-query-hooks)
```

The only major difference is that I used yarn. Here is my projenrc file
```
import { MonorepoTsProject } from "@aws/pdk/monorepo";
import {
  DocumentationFormat,
  Language,
  Library,
  ModelLanguage,
  TypeSafeApiProject,
} from "@aws/pdk/type-safe-api";
import { javascript } from "projen";

// rename variable to monorepo for better readability
const monorepo = new MonorepoTsProject({
  name: "my-project",
  packageManager: javascript.NodePackageManager.YARN_CLASSIC,
  projenrcTs: true,
});

new TypeSafeApiProject({
  parent: monorepo,
  outdir: "packages/api",
  name: "myapi",
  infrastructure: {
    language: Language.TYPESCRIPT,
  },
  model: {
    language: ModelLanguage.SMITHY,
    options: {
      smithy: {
        serviceName: {
          namespace: "com.aws",
          serviceName: "MyApi",
        },
      },
    },
  },
  runtime: {
    languages: [Language.TYPESCRIPT],
  },
  documentation: {
    formats: [DocumentationFormat.HTML_REDOC],
  },
  library: {
    libraries: [Library.TYPESCRIPT_REACT_QUERY_HOOKS],
  },
  handlers: {
    languages: [Language.TYPESCRIPT],
  },
});

monorepo.synth();
```

### Links

https://aws.github.io/aws-pdk/getting_started/your_first_aws_pdk_project.html#add-a-type-safe-api-to-your-monorepo

**Comment by nagmesh** [comment]
Based on my tests, I was able to see that error occurs in `my-project/packages/api/generated/runtime/typescript` when running pre-compile which runs the generate command. If I run the command from cli I get the same error

```
> cd ...redacted/my-project/packages/api/generated/runtime/typescript
> pdk type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs "typescript" --metadata '{"srcDir":"src"}'
yarn run v1.22.22
$ ...redacted/my-project/node_modules/.bin/type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs typescript --metadata '{"srcDir":"src"}'
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1175:7)
    at ...redacted/my-project/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45565:84
    at Array.map (<anonymous>)
    at ...redacted/my-project/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45565:65
    at Array.flatMap (<anonymous>)
    at generate_next_default (...redacted/my-project/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45562:39)
    at async ...redacted/my-project/node_modules/@aws/pdk/scripts/type-safe-api/run.js:45587:14 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.8.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
...redacted//.nvm/versions/node/v20.8.0/lib/node_modules/@aws/pdk/node_modules/execa/index.js:212
                throw error;
                ^

Error: Command failed with exit code 1: yarn type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs typescript --metadata {"srcDir":"src"}
    at makeError (...redacted//.nvm/versions/node/v20.8.0/lib/node_modules/@aws/pdk/node_modules/execa/lib/error.js:60:11)
    at module.exports.sync (...redacted//.nvm/versions/node/v20.8.0/lib/node_modules/@aws/pdk/node_modules/execa/index.js:194:17)
    at module.exports.commandSync (...redacted//.nvm/versions/node/v20.8.0/lib/node_modules/@aws/pdk/node_modules/execa/index.js:235:15)
    at Object.<anonymous> (...redacted//.nvm/versions/node/v20.8.0/lib/node_modules/@aws/pdk/_scripts/exec-command.js:41:11)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  shortMessage: 'Command failed with exit code 1: yarn type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs typescript --metadata {"srcDir":"src"}',
  command: 'yarn type-safe-api generate --specPath ../../../model/.api.json --outputPath . --templateDirs typescript --metadata {"srcDir":"src"}',
  escapedCommand: 'yarn type-safe-api generate --specPath "../../../model/.api.json" --outputPath . --templateDirs typescript --metadata "{\\"srcDir\\":\\"src\\"}"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v20.8.0

```

I have tried yarn/npm/pnpm and I can replicate the error
```
> yarn --version
1.22.22
> npm --version
10.1.0
> node -v
v20.8.0
> pnpm -v
8.15.9
```

**Comment by cogwirrel** [comment]
Thanks for your time debugging this Nagmesh! It appears that `fs.readdirSync` returns `dirents` which have different interfaces depending on the node version used! Node `20.8.0` is missing `parentPath` and instead has the deprecated `path` member: https://nodejs.org/api/fs.html#class-fsdirent

I'll raise a PR to fall back to `path` if `parentPath` is missing so we're more robust to different node versions.
